### ISSUE TITLE
Notify downstream of upcoming changes

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/text-multimarkdown#8]
### uses object interface

- [x] [Text-Markup](https://metacpan.org/pod/Text::Markup) - ([GitHub issue](https://github.com/theory/text-markup/issues/29)) - 2024-02  - tests pass
- [x] [MojoMojo](https://metacpan.org/pod/MojoMojo) - ([GitHub issue](https://github.com/mojomojo/mojomojo/issues/157)) - 2017-05 - cannot even run Makefile.PL
- [x] [Email-Simple-Markdown](https://metacpan.org/pod/Email::Simple::Markdown) - ([GitHub issue](https://github.com/yanick/Email-Simple-Markdown/issues/10)) - 2022-10

### uses functional markdown

- [x] [App-unbelievable](https://metacpan.org/pod/App::unbelievable) - ([GitHub issue](https://github.com/cxw42/unbelievable/issues/7)) - 2020-02 - tests pass
- [x] [HiD](https://metacpan.org/pod/HiD) - ([GitHub issue](https://github.com/genehack/HiD/issues/49)) - 2018-05 - no new test failures, but tests do not pass out of the box
- [x] [Plerd](https://metacpan.org/pod/Plerd) - ([GitHub issue](https://github.com/jmacdotorg/plerd/issues/59)) - 2019-12 - tests pass after force installing Web::Microformats2 and Web::Mention
- [x] [Template-Caribou](https://metacpan.org/pod/Template::Caribou) - ([GitHub issue](https://github.com/yanick/Template-Caribou/issues/12)) - 2023-10 - tests pass

## comes up in reverse deps but doesn't use it?

- [ ] [HiD-Generator-BibtexPage](https://metacpan.org/pod/HiD::Generator::BibtexPage) - https://trac.federationhq.de/git/HiD-BibtexPage.git - 2021-02 (doesn't use this?)
- [ ] [Dancer2-Template-Caribou](https://metacpan.org/pod/Dancer2::Template::Caribou) - https://github.com/yanick/Dancer2-Template-Caribou - 2023-10 (doesn't use this?)
- [ ] [PGXN-API](https://metacpan.org/pod/PGXN::API) -https://github.com/pgxn/pgxn-api/ - 2024-03 (doesn't use this?)

## those that probably won't update

- [ ] [Acme-Mom-Yours](https://metacpan.org/pod/Acme::Mom::Yours) - 2009-04
- [x] [App-Chronicle](https://metacpan.org/pod/App::Chronicle)  -  archived repo - 2020-04
- [ ] [App-Dapper](https://metacpan.org/pod/App::Dapper) - https://github.com/markdbenson/dapper - 2014-03
- [ ] [Beagle](https://metacpan.org/pod/Beagle) - 2011-08
- [ ] [Dancer-Template-Caribou](https://metacpan.org/pod/Dancer::Template::Caribou) - https://github.com/yanick/Dancer-Template-Caribou - 2017-04
- [ ] [Dist-Zilla-Plugin-JSAN](https://metacpan.org/pod/Dist::Zilla::Plugin::JSAN) - 2011-07
- [ ] [Dist-Zilla-Plugin-Web](https://metacpan.org/pod/Dist::Zilla::Plugin::Web) - https://github.com/SamuraiJack/Dist-Zilla-Plugin-Web - 2015-08
- [ ] [Doc-Simply](https://metacpan.org/pod/Doc::Simply) - 2010-07
- [ ] [HiD-Generator-GitRepositories](https://metacpan.org/pod/HiD::Generator::GitRepositories) - https://gitcloud.federationhq.de/git/HiD-GitRepositories.git -2018-07
- [ ] [HiD-Generator-Sass](https://metacpan.org/pod/HiD::Generator::Sass)- 2016-03
- [ ] [Mira](https://metacpan.org/pod/Mira) - https://github.com/kiamazi/mira - 2018-05
- [ ] [Miril](https://metacpan.org/pod/Miril) - 2010-09
- [ ] [Module-Build-JSAN-Installable](https://metacpan.org/pod/Module::Build::JSAN::Installable) - 2010-08
- [ ] [Module-JSAN](https://metacpan.org/pod/Module::JSAN) - 2010-01
- [ ] [Mojito](https://metacpan.org/pod/Mojito) - 2017-12
- [ ] [Perl-Achievements](https://metacpan.org/pod/Perl::Achievements) - 2012-05
- [ ] [Rubric-Entry-Formatter-Markdown](https://metacpan.org/pod/Rubric::Entry::Formatter::Markdown) - 2013-10
- [x] [Task-BeLike-MELO](https://metacpan.org/pod/Task::BeLike::MELO) - doesn't use in code
- [x] [Task-BeLike-SARTAK](https://metacpan.org/pod/Task::BeLike::SARTAK) - doesn't use in code
- [ ] [Template-Plugin-MultiMarkdown](https://metacpan.org/pod/Template::Plugin::MultiMarkdown) - https://github.com/barbie/template-plugin-multimarkdown - 2015-04
- [ ] [Text-MultiMarkdown-ApacheHandler](https://metacpan.org/pod/Text-MultiMarkdown-ApacheHandler) - 2006-08
- [ ] [Text-Xslate-Bridge-MultiMarkdown](https://metacpan.org/pod/Text::Xslate::Bridge::MultiMarkdown) -https://github.com/throughnothing/Text-Xslate-Bridge-MultiMarkdown/ - 2013-08
- [ ] [Yukki](https://metacpan.org/pod/Yukki) - 2015-01

**Comment by briandfoy** [comment]
I've tested the current releases of these modules with the latest dev version of Text::MultiMarkdown. There's nothing else to do for this issue, and downstream breakages that we discover later can report new issues.
